### ISSUE TITLE
Can you guide how to add language.

### ISSUE THREAD

**Issue by haven-jeon** [atomrpg/modkit#11]
When I see Japanese.

```
$ ls -al *ja*
patch_strings_ja.json       strings_ja.json       text_ja.json       text_override_ja.json
patch_strings_ja.json.meta  strings_ja.json.meta  text_ja.json.meta  text_override_ja.json.meta
```

Where can I get `*.meta` file, especially guid? 

Thanks

**Comment by deniskak** [comment]
> When I see Japanese.
> 
> ```
> $ ls -al *ja*
> patch_strings_ja.json       strings_ja.json       text_ja.json       text_override_ja.json
> patch_strings_ja.json.meta  strings_ja.json.meta  text_ja.json.meta  text_override_ja.json.meta
> ```
> 
> Where can I get `*.meta` file, especially guid?

 I believe these files are added by Unity whenever it indexes the files appearing in the "Assets" directory. I.e. you add a file to "Assets", go to Unity Editor, it automatically picks a new file/directory and generates a corresponding metafile.

**Comment by haven-jeon** [comment]
Thanks.
