### ISSUE TITLE
При попытке собрать мод возникает ошибка

### ISSUE THREAD

**Issue by Positiff88** [atomrpg/modkit#14]
Assets\Scripts\PlayInEditor.cs(11,19): error CS0234: The type or namespace name 'SceneManagement' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

Похоже, что для исправления ошибки код
`using UnityEditor.SceneManagement;`
должен быть помещён внутри блока
```
#if UNITY_EDITOR
using UnityEditor;
#endif
```

**Comment by atomrpg** [comment]
Fixed.
