### ISSUE TITLE
Asset Viewer sorting

### ISSUE THREAD

**Issue by phobos2077** [atomrpg/modkit#2]
Would be nice to be able to search assets by name and/or filter them by type. Right now it's a bit hard to find what you want (or maybe I failed to find how?).

**Comment by atomrpg** [comment]
> Would be nice to be able to search assets by name and/or filter them by type. Right now it's a bit hard to find what you want (or maybe I failed to find how?).

Planned - search by name, other improvements will be discussed or pull request. [source included in repo] AssetViewer.cs

**Comment by phobos2077** [comment]
Didn't notice that script, that's great! :+1:

**Comment by atomrpg** [comment]
thank you for improving @phobos2077 ;)
