### ISSUE TITLE
Could not extract GUID in text file

### ISSUE THREAD

**Issue by phobos2077** [atomrpg/modkit#4]
Get this error in console after "downloading" some assets:

`Could not extract GUID in text file Assets/Resources/Entities/Weapon/zatochka.asset at line 12.`

This seem to happen after some time (maybe after assets are re-loaded from the bundles?)

**Comment by atomrpg** [comment]
Ready to use:
+AmmoProto
+ItemProto
+CharacterProto

**Comment by atomrpg** [comment]
+other prototype
