### ISSUE TITLE
Unity crashes after closing Node Editor

### ISSUE THREAD

**Issue by phobos2077** [atomrpg/modkit#7]
Not sure if anything can be done about it or if it's purely Unity's fault, but sometimes right when I close a Node Editor for some behavior, Unity crashes:

![](https://i.imgur.com/H1SsmBC.png)

Seems to happen consistently in following case:

- In AssetViewer click on "KRZ.Trader_1"
- Open "Node Editor" via Inspector
- Click on any `InventorySet` node
- Expand "Items"
- Press X to close Node Editor window

**Comment by atomrpg** [comment]
Node Editor can't support any changes in temporary resources, request: non-edit mode.

**Comment by atomrpg** [comment]
fix version: 0.07
