### ISSUE TITLE
Unable to scroll in Node Editor node view

### ISSUE THREAD

**Issue by phobos2077** [atomrpg/modkit#9]
Trying to view an InventorySet for a trader. Expanded the "Inventory" list in the node view, but unable to fully view it because upon scrolling down, it immediately scrolls back up.

![](https://i.imgur.com/8zWE5Fw.png)

The same happens in "Edit" mode after I downloaded the asset.

**Comment by atomrpg** [comment]
Fix version: 0.07 scroll fix
